#DB_NAME: demoDb
#DB_SERVER: localhost
#DB_PORT: 3306
#DB_USERNAME: root
#DB_PASSWORD: 31323334

server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://${DB_SERVER}:${DB_PORT:3306}/${DB_NAME}
#    url: jdbc:mysql://localhost:3306/demoDb?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
#    password: 31323334
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect